# Generated by Django 4.2.1 on 2023-05-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
    ]
