# Generated by Django 4.2.1 on 2023-05-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_part_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Song Title'),
        ),
    ]
